version: '3.8'

services:
  config-server:
    build:
      context: ./microservices-config
    ports:
      - "8888:8888"
    networks:
      - microservices-network

  eureka-server:
    build:
      context: ./microservices-eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    depends_on:
      - config-server

  admin-server:
    build:
      context: ./microservices-admin
    ports:
      - "9090:9090"
    networks:
      - microservices-network
    depends_on:
      - config-server
      - eureka-server

  gateway:
    build:
      context: ./microservices-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - config-server
      - eureka-server

  retail-service:
    build:
      context: ./microservice-retail
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - config-server
      - eureka-server
      - postgres_db

  postgres_db:
    container_name: java_db
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge