version: '4.2'

services:
  postgres_db:
    container_name: java_db
    image: luischumi/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    networks:
      - microservices-network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

  config-server:
    image: luischumi/microservicio-ista-config-server:latest
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    depends_on:
      - postgres_db

  eureka-server:
    image: luischumi/microservicio-ista-eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    depends_on:
      - config-server

  admin-server:
    image: luischumi/microservicio-ista-admin-server:latest
    ports:
      - "9090:9090"
    networks:
      - microservices-network
    depends_on:
      - eureka-server

  gateway:
    image: luischumi/microservicio-ista-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - admin-server

  retail-service:
    image: luischumi/microservicio-ista-retail-service:latest
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - gateway

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data:
