server:
  port: 8081

spring:
  application:
    name: msvc-retail

  datasource:
    url: jdbc:postgresql://java_db:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,logfile"
        exclude: "beans,env,threaddump"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0

logging:
  level:
    root: info
    com:
      cumple:
        pos: debug